server:
  port: 10001

spring:
  # 数据库配置 - dev2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.80.200:3306/rbac_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Abc123123

  # Redis 配置 - dev2
  data:
    redis:
      host: 192.168.80.200
      port: 6379
      database: 0
      password:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开发环境打印SQL