spring:
  profiles:
    # 这里决定当前启动哪个环境。
    active: dev1

  threads:
    virtual:
      enabled: true  # 虚拟线程通常所有环境都开启

# MyBatis Plus 公共逻辑配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: cn.kmdckj.base
  configuration:
    map-underscore-to-camel-case: true