server:
  port: 10002

spring:
  # 数据库配置 - dev1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.80.200:3306/base?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Abc123123

  # Redis 配置 - dev1
  data:
    redis:
      host: 192.168.80.200
      port: 6379
      database: 0
      password:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开发环境打印SQL