server:
  port: 10086  # 1. ??????? 10086

spring:
  threads:
    virtual:
      enabled: true  # ??????
  autoconfigure:
    exclude:
      # 1. ???????
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      # 2. ???????
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      # 3. ?? MyBatis Plus
      - com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration
      # 4. ?? Redis
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration